# Generated by Django 3.2.9 on 2022-04-11 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulartour',
            name='status',
            field=models.CharField(choices=[('waiting', 'In pending'), ('start', 'In process'), ('completed', 'Finished'), ('canceled', 'Canceled')], default='waiting', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=9, verbose_name='Mobile phone number')),
                ('place_count', models.PositiveSmallIntegerField(verbose_name='Places')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='new', max_length=9, verbose_name='Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('notice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional information')),
                ('regular_tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tours.regulartour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
